#!/bin/bash
# Script 5: Open Source Manifesto Generator (Simplified)
# Author: SAHIL PRACHAND| Course: Open Source Software
# Description: Creates a personalized open-source statement
# Concepts: read for input, variables, date, file I/O (>)

echo ""
echo "╔════════════════════════════════════════╗"
echo "║  OPEN SOURCE MANIFESTO GENERATOR       ║"
echo "╚════════════════════════════════════════╝"
echo ""

# Get user input
read -p "1. Favorite open-source tool: " TOOL
read -p "2. What does freedom mean to you: " FREEDOM
read -p "3. One thing you'd build and share: " BUILD
echo ""

# Generate metadata
DATE=$(date '+%d %B %Y')
USERNAME=$(whoami)
OUTPUT_FILE="manifesto_${USERNAME}.txt"

# Create manifesto
MANIFESTO="PERSONAL OPEN SOURCE MANIFESTO
Generated by: $USERNAME
Date: $DATE

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

I believe in $TOOL because it represents $FREEDOM.

Every day, I use tools built by people who chose to share their work openly. I stand on their shoulders. In return, I commit to building $BUILD and sharing it freely—not for profit, but because collective knowledge is stronger than locked code.

Open source is a promise: that tools remain free, code stays transparent, and knowledge belongs to everyone.

This is my commitment to the open-source movement.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Save to file
echo "$MANIFESTO" > "$OUTPUT_FILE"

# Display result
echo "✓ Manifesto created!"
echo ""
cat "$OUTPUT_FILE"
echo ""
echo "Saved to: $OUTPUT_FILE"
echo ""